with asianCountriesCTE as (
select CO.NAME AS COUNTRYNAME, CI.NAME AS CITYNAME,CO.POPULATION AS COUNTRYPOPULATION,CI.POPULATION AS CITYPOPULATION 
from country CO
left join city CI ON CO.CODE = CI.COUNTRYCODE
where continent = 'Asia' 
)
SELECT SUM(CITYPOPULATION)
FROM asianCountriesCTE;
