with CountriesCTE as (
select CO.CONTINENT AS CONTINENT, CI.NAME AS CITYNAME,CO.POPULATION AS COUNTRYPOPULATION,CI.POPULATION AS CITYPOPULATION 
from country CO
join city CI ON CO.CODE = CI.COUNTRYCODE
)
SELECT CONTINENT,ROUND(AVG(CITYPOPULATION),2)
FROM CountriesCTE
GROUP BY CONTINENT
;
