SELECT CT.CONTEST_ID,CT.HACKER_ID,CT.NAME,SUM(TOTAL_SUBMISSIONS),SUM(TOTAL_ACCEPTED_SUBMISSIONS),SUM(TOTAL_VIEWS),SUM(TOTAL_UNIQUE_VIEWS)
FROM CONTESTS AS CT 
INNER JOIN COLLEGES AS CO ON CT.CONTEST_ID = CO.CONTEST_ID
INNER JOIN CHALLENGES AS CH ON CO.COLLEGE_ID = CH.COLLEGE_ID
LEFT OUTER JOIN 
(SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS,SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS 
 FROM SUBMISSION_STATS 
 GROUP BY CHALLENGE_ID) AS SS ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
 
 LEFT OUTER JOIN 
 
(SELECT CHALLENGE_ID,SUM(TOTAL_VIEWS) AS TOTAL_VIEWS,SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
FROM VIEW_STATS
GROUP BY CHALLENGE_ID 
) AS VS ON CH.CHALLENGE_ID=VS.CHALLENGE_ID

GROUP BY  CT.CONTEST_ID,CT.HACKER_ID,CT.NAME
HAVING (SUM(TOTAL_SUBMISSIONS)+
        SUM(TOTAL_ACCEPTED_SUBMISSIONS)+
        SUM(TOTAL_VIEWS)+
        SUM(TOTAL_UNIQUE_VIEWS)) != 0

ORDER BY CT.CONTEST_ID;


