/*
Enter your query here.
*/

SELECT E.COMPANY_CODE, C.FOUNDER, COUNT(DISTINCT E.LEAD_MANAGER_CODE ), COUNT(DISTINCT E.SENIOR_MANAGER_CODE),COUNT(DISTINCT MANAGER_CODE),COUNT(DISTINCT EMPLOYEE_CODE)
FROM EMPLOYEE AS E LEFT OUTER JOIN COMPANY C ON E.COMPANY_CODE=C.COMPANY_CODE
GROUP BY E.COMPANY_CODE,C.FOUNDER
